name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          component: true

      - name: Jest/Supertest Run
        env:
          MEDIFLOWKEY: ${{ secrets.MEDIFLOWKEY }}
        run: npm test


