name: Frontend/Backend Tests and Deployment

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci

      - name: Install Client Dependencies
        run: npm ci
      
      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          component: true

      - name: Jest/Supertest Run
        env:
          MEDIFLOWKEY: ${{ secrets.MEDIFLOWKEY }}
        run: npm test

  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Node JS
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Render Deployment
      working-directory: ./.github/workflows
      run: node deployRender.js
      env:
        API_KEY: ${{ secrets.RENDER_APIKEY }}
        SERVICE_ID: ${{ secrets.RENDER_SERVICEID }}


