name: Render Deployment On Merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Node JS
      uses: actions/setup-node@v2
      with:
        node-version: '14'  
    
    - name: Install NPM
      run: npm install

    - name: Build
      run: npm ci && npm run build  

    - name: Render Deployment
      working-directory: ./.github/workflows
      run: node deployRender.js
      env:
        API_KEY: ${{ secrets.RENDER_APIKEY }}
        SERVICE_ID: ${{ secrets.RENDER_SERVICEID }}
    
